[package]
name = "babe-grandpa-runtime"
version = "2.0.0-rc4"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A Substrate runtime that manages BABE and GRANDPA authorities and passes them to the client"

[package.metadata.substrate]
categories = [
	"runtime",
	"Babe",
	"Grandpa",
	"Runtime API",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc4"

[dependencies]
parity-scale-codec = { version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
# Substrate Pallets
babe = { package = 'pallet-babe', version = '2.0.0-rc4', default-features = false}
balances = { package = 'pallet-balances', version = '2.0.0-rc4', default-features = false }
grandpa = { package = 'pallet-grandpa', version = '2.0.0-rc4', default-features = false }
randomness-collective-flip = { package = 'pallet-randomness-collective-flip', version = '2.0.0-rc4', default-features = false }
sudo = { package = 'pallet-sudo', version = '2.0.0-rc4', default-features = false }
timestamp = { package = 'pallet-timestamp', version = '2.0.0-rc4', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', version = '2.0.0-rc4', default-features = false }
pallet-staking = {package = 'pallet-staking', version = '2.0.0-rc4' , default-features = false}
pallet-staking-reward-curve = {package='pallet-staking-reward-curve', version = '2.0.0-rc4', default-features = false}
pallet-session = {package = 'pallet-session', features = ['historical'], version='2.0.0-rc4', default-features = false}

# Other Substrate dependencies
frame-executive = { version = '2.0.0-rc4', default-features = false }
frame-support = { version = '2.0.0-rc4', default-features = false }
frame-system = { version = '2.0.0-rc4', default-features = false }
sp-api = { version = '2.0.0-rc4', default-features = false }
sp-block-builder = { version = '2.0.0-rc4', default-features = false }
sp-consensus-babe = { version = '0.8.0-rc4', default-features = false }
sp-core = { version = '2.0.0-rc4', default-features = false }
sp-finality-grandpa = { version = '2.0.0-rc4', default-features = false }
sp-inherents = { version = '2.0.0-rc4', default-features = false }
sp-io = { version = '2.0.0-rc4', default-features = false }
sp-offchain = { version = '2.0.0-rc4', default-features = false }
sp-runtime = { version = '2.0.0-rc4', default-features = false }
sp-session = { version = '2.0.0-rc4', default-features = false }
sp-staking = {version = '2.0.0-rc4', default-features = false}
sp-std = { version = '2.0.0-rc4', default-features = false }
sp-transaction-pool = { version = '2.0.0-rc4', default-features = false }
sp-version = { version = '2.0.0-rc4', default-features = false }


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# External dependencies
	"parity-scale-codec/std",
	"serde",

	# Substrate dependencies alphabetically
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	# Substrate Pallets
	"babe/std",
	"balances/std",
	"grandpa/std",
	"randomness-collective-flip/std",
	"sudo/std",
	"timestamp/std",
	"transaction-payment/std",
	"sp-staking/std",
	"pallet-staking/std",
	"pallet-session/std",

	# Recipes pallets
	# (None)
]
